[package]
name = "accountscli"
version = "0.7.0"
authors = ["ltabis <tab.rysak70@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
prettytable-rs = "^0.8.0"
serde_json = "1.0" 
chrono = "0.4"
colored = "2"