[package]
name = "tunes-cli"
version = "0.1.0"
authors = ["ltabis <ltabis.pro@gmail.com>"]
edition = "2021"
description = "A cli to register and analyze monetary transactions"
license-file = "../LICENSE"
documentation = "https://docs.rs/"
homepage = "https://github.com/ltabis/accounts-cli"
repository = "https://github.com/ltabis/accounts-cli"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
toml = "0.8"
clap = { version = "4.5", features = ["derive"] }
time = { version = "0.3", features = ["std", "parsing", "formatting", "serde"] }
time-macros = { version = "0.2", features = ["parsing"] }
rhai-http = { version = "0.2" }
rhai = { version = "1.18" }
